[package]
name = "soluai"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-files = "0.6.6"
actix-web = "4.8.0"
image = "0.25.2"
ndarray = "0.15.6"
ort = "2.0.0-rc.1"
serde = { version = "1.0.204", features = ["derive"] }